# Generated by Django 5.1.2 on 2024-10-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the user.', max_length=254)),
                ('email', models.EmailField(help_text="The user's email address.", max_length=254)),
                ('subject', models.CharField(help_text='The subject of the message.', max_length=254)),
                ('message', models.TextField(help_text='The message content.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the message was sent.')),
            ],
        ),
    ]
