# Generated by Django 5.1.2 on 2024-10-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (SKU) used to uniquely identify the product.', max_length=254, null=True)),
                ('name', models.CharField(help_text='Name of the product.', max_length=254)),
                ('description', models.TextField(help_text='Detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Customer rating for the product, if available.', max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, help_text='URL for the product image if hosted externally.', max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the product.', null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, help_text='ForeignKey to Category, allowing each product to belong to one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
