# Generated by Django 5.1.2 on 2024-10-19 22:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the product. Stored in Cloudinary.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
